cloudwego/hertz-examples

README.md
README_CN.md

docs
Linked every example in README to the respective folder.
#4 Proposal: add link for each example in README

docs: add links for every example title in README  #4

---

tracer/README.md

feat: add tracer graph

---

README.md
README_CN.md
multiple_service/README.md
multiple_service/main.go

feat: add multiple_service example

feat: add multiple_service example

---

opentelemetry/README.md
opentelemetry/otel-collector-config.yaml

docs: Documentation only changes
Some systems do not have the default domain name :`host.docker.internal`

fix(doc): host.docker.internal -> victoriametrics

---

go.mod
go.sum
middleware/README.md
middleware/pprof/README.md
middleware/pprof/custom_prefix/server.go
middleware/pprof/custom_router_group/server.go
middleware/pprof/default/server.go

feat: add pprof example
en: add pprof example
zh: 增加pprof示例代码

feat: add pprof example

---

bizdemo/hertz_gorm/readme.md

docs: Documentation only changes
en: change the error way to start hertz_gorm
zh: 修改readme错误的启动方式

doc: correct incorrect readme

---

bizdemo/hertz_jwt/biz/handler/ping.go
bizdemo/hertz_jwt/biz/mw/jwt.go

optimize
为 hertz_jwt 的 jwt 中间件增加 IdentityHandler 配置参数，更清晰展示如何从 token 中提取用户信息。

optimize: append IdentityHandler for hertz_jwt

---

route/main.go

feat: A new feature
en: add example for `Handle`
zh: 添加路由注册 `Handle` 方法的使用示例
Fixes(https://github.com/cloudwego/hertz/issues/392)

feat: add route Handle example

---

file/html-fs/README.md
file/html-fs/assets/css/style.css
file/html-fs/main.go
file/html-fs/views/index.html
file/html/README.md
file/html/assets/css/style.css
file/html/main.go
file/html/views/index.html
file/staticFile/main.go

Optimizes example for Static and StaticFS using html and assets as example and fixes https://github.com/cloudwego/hertz/issues/400

feat: improve fs example

---

.github/workflows/pr-check.yml
go.mod
go.sum
middleware/requestid/custom_generator/main.go
middleware/requestid/custom_handler/main.go
middleware/requestid/get_requestid/main.go

feat: A new feature
zh: 升级requestid中间件版本并对代码进行适配
null

feat: upgrade requestid mw version and adapt

---

README.md
README_CN.md
go.mod
go.sum
middleware/README.md
middleware/csrf/README.md
middleware/csrf/custom_errorfunc/main.go
middleware/csrf/custom_extractor/main.go
middleware/csrf/custom_ignoremethods/main.go
middleware/csrf/custom_keylookup/main.go
middleware/csrf/custom_next/main.go
middleware/csrf/custom_secret/main.go
middleware/csrf/default/main.go

feat
en:  Add example of `csrf` middleware
zh: 添加了 `csrf` 中间件的例子
null

feat: add csrf example

---

bizdemo/hertz_jwt/Makefile
bizdemo/hertz_session/Makefile

optimize
Refer to https://github.com/cloudwego/hertz/issues/529
https://github.com/cloudwego/hertz/issues/529

optimize: improve makefile

---

README.md
client/send_request/README.md
file/download/main.go

- style
- 总体的README.md文档描述不够清晰，让初看的人（比如我）有点懵，所以我在搞懂流程之后想补充完整。
- client/send_request/README.md中的client错拼成了cient
- 更新了文档，说明了归类为Bizdemo的文件的正确位置。
- 纠正了单词拼写

update the README.md,correct the file position of bizdemo

---

README.md
README_CN.md

docs: Documentation only changes
zh: 更正错误的链接
null

docs(readme): correct wrong link

---

hz/plugin/proto/router.go
opentelemetry/kitex/server/main.go

fix
kitex中的otel-provider的包导成了hertz里面的otel-provider包了，虽然两个包之间代码没有什么不同，但是为了避免今后包产生差异，还是改一下包名为好

fix(opentelemetry): import err

---

README.md
go.mod
go.sum
trailer/README.md
trailer/main.go

feat
en: Add example of read/write `Trailer`
zh: 添加了读/写`Trailer`的例子

feat: add trailer example

---

monitoring/docker-compose.yml
monitoring/prometheus.yml

solve question: https://github.com/hertz-contrib/monitor-prometheus/issues/5

update: config file

---

bizdemo/tiktok_demo/.gitignore
bizdemo/tiktok_demo/README.md

docs
add maintainer in README of tiktok_demo
null

update: add maintainer in README of tiktok_demo

---

hlog/logrus/main.go
hlog/standard/main.go
hlog/zap/main.go
hlog/zerolog/main.go

feat&&docs
en: add the descriptions of the output in hlog examples
cn: 添加了 hlog 示例中关于输出位置的示例

feat: add the descriptions of the output in hlog examples

---

hz/hz_client/client/hertz_gen/toutiao/middleware/hzClient/hertz/hertz_client.go

fix: Calling the StatusCode function correctly

---

README_CN.md

docs
- zh: 删除重复行
- en:remove duplicated line

fix: remove duplicated line

---

bizdemo/hertz_session/biz/handler/user/user_service.go

fix: A bug fix
en: Correct incorrect comments
null

fix: correct incorrect comments

---

go.mod
render/text/README.md
render/text/main.go
render/xml/README.md
render/xml/main.go
render/yaml_customize/README.md
render/yaml_customize/main.go

feat
- zh:  添加 xml，string渲染的示例以及自定义实现yaml渲染的示例
- en

feat:add xml,text,customizing render examples

---

bizdemo/hertz_gorm/docker-compose.yml
bizdemo/hertz_gorm/readme.md
bizdemo/hertz_gorm_gen/docker-compose.yml
bizdemo/hertz_gorm_gen/readme.md
bizdemo/hertz_jwt/docker-compose.yml
bizdemo/hertz_jwt/readme.md

optimize: A new optimization
en: automatically initialize MySQL for `hertz_gorm`, `hertz_gorm_gen` and `hertz_jwt`
null

optimize: automatically initialize mysql

---

client/forward_proxy/README.md

fix: fix client/forward_proxy/README.md link error

---

README.md
README_CN.md
client/forward_proxy/README.md

docs: more example link

---

opentelemetry/README.md
opentelemetry/docker-compose.yaml
opentelemetry/otel-collector-config.yaml

optimize
https://github.com/cloudwego/hertz-examples/issues/115

optimize: update otel config.yaml

---

opentelemetry/docker-compose.yaml

fix: Fix opentelemetry docker-compose config

fix(opentelemetry): fix opentelemetry docker-compose config

---

hz/struct_reuse/thrift_reuse/README.md

feat
add README for struct_reuse
Fix #127

feat: add README for struct_reuse

---

bizdemo/hertz_gorm/biz/handler/user_gorm/user_service.go
bizdemo/tiktok_demo/biz/dal/db/message.go
bizdemo/tiktok_demo/biz/handler/favorite/favorite_handler.go
bizdemo/tiktok_demo/biz/handler/relation/relation_handler.go
bizdemo/tiktok_demo/biz/service/favorite/favorite_service.go

optimize
update return status code in hertz_gorm

update return status code in hertz_gorm

---

reverseproxy/tls/README.md
reverseproxy/tls/main.go

fix
zh: 修复无法使用 reverseproxy tls server 的 example, 添加了 readme

fix: reverse proxy tls server start fail

---

.github/workflows/pr-check.yml
.github/workflows/tests.yml
bizdemo/tiktok_demo/biz/handler/favorite/favorite_handler.go
bizdemo/tiktok_demo/biz/router/favorite/middleware.go
hz_kitex_demo/hertz-server/biz/handler/api/student_api.go
hz_kitex_demo/hertz-server/infra/rpc/client.go
hz_kitex_demo/hertz-server/main.go

chore: make rpc client global

---

middleware/loadbalance/round_robin/client/main.go

fix: change client to cli in the loadbalance/round_robin example

---

sse/README.md
sse/client/main.go
sse/server/main.go

feat: sse demo

---

bizdemo/hertz_gorm/biz/handler/user_gorm/user_service.go
bizdemo/hertz_gorm/biz/hertz_gen/user_gorm/api.go
bizdemo/hertz_gorm/idl/api.thrift
bizdemo/hertz_gorm_gen/cmd/generate.go

ref [bizdemo/hertz_gorm_gen/readme.md](https://github.com/cloudwego/hertz-examples/blob/main/bizdemo/hertz_gorm_gen/readme.md#quick-start)
```bash
cd bizdemo/hertz_gorm_gen/cmd
go run generate.go
```
Origin bizdemo/hertz_gorm_gen/cmd/generate.go
```
g := gen.NewGenerator(gen.Config{
OutPath: "./biz/model/query",
Mode:    gen.WithoutContext | gen.WithDefaultQuery | gen.WithQueryInterface, // generate mode
})
```
Will generate code under the wrong directory.
Also fix some spell errors :)

fix: Fix path error
